<?php

namespace AppBundle\Repository;

/**
 * CarteMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarteMenuRepository extends \Doctrine\ORM\EntityRepository
{
}
