<?php

namespace AppBundle\Repository;

/**
 * CarteMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarteMenuRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSandwichMenu($idMenu)
    {
        # code...
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s FROM AppBundle:Sandwich s Where s.carteMenu = :ids'
            )
            ->setParameter('ids', $idMenu)
            ->getResult();
    }
}
