<?php

namespace AppBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAllCommandesForUser($id_user)
	{
		$sql = " SELECT * FROM commande WHERE id = :id_user ORDER BY id DESC";

		$em = $this->getEntityManager();
		$dbh = $em->getConnection();
		$query = $dbh->prepare($sql);
		$results = $query->execute([":id_user" => $id_user]);
		$results = $query->fetchAll();

		return $results;
	}

	public function insert($commande)
	{

		// dump($commande);

		$sql = 'INSERT INTO commande VALUES ( null , :id_panier, :id_address, :processed, :livre, NOW())';

		$em = $this->getEntityManager();
		$dbh = $em->getConnection();
		$query = $dbh->prepare($sql);
		
		$results = $query->execute([
										":id_panier" => $commande->getPanier()->getId(),
										":id_address" => $commande->getAdresseLivraison() ?  $commande->getAdresseLivraison()->getId() : null,
										":processed" => $commande->getProcessed(),
										":livre" => $commande->getLivree(),
									]);

		// dump($query);
		return true;
	}
}
