<?php

namespace AppBundle\Repository;

/**
 * GarnitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GarnitureRepository extends \Doctrine\ORM\EntityRepository
{
}
