<?php
namespace AppBundle\Repository;
/**
 * LignePanierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LignePanierRepository extends \Doctrine\ORM\EntityRepository
{
    // PRoblem here !
    public function find_lines($panier_id)
    {
     	
        $sql =
        'SELECT DISTINCT *
        FROM ligne_panier
        LEFT JOIN sandwich ON ligne_panier.sandwich_id = sandwich.id
        LEFT JOIN sandwich_garniture ON sandwich_garniture.sandwich_id = sandwich.id
        LEFT JOIN pain ON sandwich.pain_id = pain.id
        WHERE ligne_panier.id = :panier_id';

        $em = $this->getEntityManager();
        $dbh = $em->getConnection();
        $query = $dbh->prepare($sql);
        $results = $query->execute([":panier_id" => $panier_id]);
        $results = $query->fetchAll();

        return $results;
    }
}