<?php

namespace AppBundle\Repository;

/**
 * PainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PainRepository extends \Doctrine\ORM\EntityRepository
{
}
