<?php

namespace AppBundle\Repository;

/**
 * PanierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanierRepository extends \Doctrine\ORM\EntityRepository
{

	// We should use find($id)
	// public function getPanierById($id)
	// {
	// 	$sql = 'SELECT s FROM AppBundle:Sandwich s Where s.id = :id';
	// 	return $this->getEntityManager()->createQuery($sql)->setParameter(':id', $id)->getResult();
	// }

	public function getPanierForUser($user_id)
	{
		$sql = 'SELECT p FROM AppBundle:Panier p WHERE p.utilisateur = :id';
		return $this->getEntityManager()->createQuery($sql)->setParameter(':id', $user_id)->getResult();
	}

	public function savePanierForUser($user_id, $panier_infos)
	{
		$sql = "
					INSERT INTO
					VALUES 
		";

		$em = $this->getEntityManager();
		$dbh = $em->getConnection();
		
		$query = $dbh->prepare($sql);
		$query->execute();
	}
}
