<?php

namespace AppBundle\Repository;

/**
 * SandwichGarnitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SandwichGarnitureRepository extends \Doctrine\ORM\EntityRepository
{
}
