<?php

namespace AppBundle\Repository;

/**
 * SandwichRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SandwichRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSandwichWithId($_id) {

        return $this->getEntityManager()
                    ->createQuery(
                        'SELECT s FROM AppBundle:Sandwich s Where s.id = :ids'
                    )
                    ->setParameter('ids', $_id)
                    ->getResult();
    }
}
