<?php

namespace AppBundle\Repository;

/**
 * SandwichRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SandwichRepository extends \Doctrine\ORM\EntityRepository
{
}
