<?php

namespace AppBundle\Repository;

/**
 * TypeGarnitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeGarnitureRepository extends \Doctrine\ORM\EntityRepository
{
}
