services:
#    app.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    app.catalogue:
        class: AppBundle\Service\CatalogueManager
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'



