-- MySQL Script generated by MySQL Workbench
-- 09/26/17 20:50:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema projet_dev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projet_dev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projet_dev` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cartes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cartes` (
  `id` INT NOT NULL,
  `nom` VARCHAR(100) NOT NULL,
  `promoted` BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC))
ENGINE = InnoDB;

USE `projet_dev` ;

-- -----------------------------------------------------
-- Table `projet_dev`.`membres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_dev`.`membres` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `prenom` VARCHAR(100) NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NULL DEFAULT NULL,
  `connecte` TINYINT(1) UNSIGNED NULL DEFAULT NULL,
  `newsletter` BIT(1) NOT NULL DEFAULT b'0',
  `date_inscription` DATE NULL DEFAULT NULL,
  `banned` BIT(1) NOT NULL DEFAULT b'0',
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projet_dev`.`adresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_dev`.`adresses` (
  `id` BIGINT(20) UNSIGNED NOT NULL,
  `membres_id` BIGINT(20) UNSIGNED NOT NULL,
  `code_postal` VARCHAR(20) NOT NULL,
  `ville` VARCHAR(100) NULL DEFAULT NULL,
  `rue` VARCHAR(255) NULL DEFAULT NULL,
  `numero` INT(10) UNSIGNED NULL DEFAULT NULL,
  `role` VARCHAR(50) NOT NULL,
  `commentaire` VARCHAR(255) NULL,
  PRIMARY KEY (`id`, `membres_id`),
  INDEX `fk_adresses_membres1_idx` (`membres_id` ASC),
  CONSTRAINT `fk_adresses_membres1`
    FOREIGN KEY (`membres_id`)
    REFERENCES `projet_dev`.`membres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projet_dev`.`commandes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_dev`.`commandes` (
  `id` INT(11) NOT NULL,
  `membres_personne_id` BIGINT(20) UNSIGNED NOT NULL,
  `adresses_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_commandes_membres1_idx` (`membres_personne_id` ASC),
  INDEX `fk_commandes_adresses1_idx` (`adresses_id` ASC),
  CONSTRAINT `fk_commandes_membres1`
    FOREIGN KEY (`membres_personne_id`)
    REFERENCES `projet_dev`.`membres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commandes_adresses1`
    FOREIGN KEY (`adresses_id`)
    REFERENCES `projet_dev`.`adresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projet_dev`.`garnitures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_dev`.`garnitures` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `prix` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projet_dev`.`pains`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_dev`.`pains` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `prix` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projet_dev`.`sandwiches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_dev`.`sandwiches` (
  `id` INT(10) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `pains_id` INT(10) UNSIGNED NOT NULL,
  `taille_cm` INT(11) NULL DEFAULT NULL,
  `garniture_sandwich_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sandwiches_pains1_idx` (`pains_id` ASC),
  CONSTRAINT `fk_sandwiches_pains1`
    FOREIGN KEY (`pains_id`)
    REFERENCES `projet_dev`.`pains` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projet_dev`.`garnitures_sandwich`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_dev`.`garnitures_sandwich` (
  `id` INT(11) NOT NULL,
  `sandwiches_id` INT(10) UNSIGNED ZEROFILL NOT NULL,
  `garnitures_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`sandwiches_id`, `garnitures_id`, `id`),
  INDEX `fk_table1_garnitures1_idx` (`garnitures_id` ASC),
  CONSTRAINT `fk_table1_garnitures1`
    FOREIGN KEY (`garnitures_id`)
    REFERENCES `projet_dev`.`garnitures` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_table1_sandwiches1`
    FOREIGN KEY (`sandwiches_id`)
    REFERENCES `projet_dev`.`sandwiches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projet_dev`.`ligne_commandes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_dev`.`ligne_commandes` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `commandes_id` INT(11) NOT NULL,
  `sandwiches_id` INT(10) UNSIGNED ZEROFILL NOT NULL,
  `quantite` INT(11) NULL DEFAULT NULL,
  `prix_unitaire` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `commandes_id`),
  INDEX `fk_ligne_commandes_sandwiches1_idx` (`sandwiches_id` ASC),
  INDEX `fk_ligne_commandes_commandes1_idx` (`commandes_id` ASC),
  CONSTRAINT `fk_ligne_commandes_sandwiches1`
    FOREIGN KEY (`sandwiches_id`)
    REFERENCES `projet_dev`.`sandwiches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ligne_commandes_commandes1`
    FOREIGN KEY (`commandes_id`)
    REFERENCES `projet_dev`.`commandes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projet_dev`.`telephones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_dev`.`telephones` (
  `id` BIGINT(20) UNSIGNED NOT NULL,
  `membres_id` BIGINT(20) UNSIGNED NOT NULL,
  `numero` VARCHAR(255) NOT NULL,
  `role` VARCHAR(50) NOT NULL,
  `commentaire` VARCHAR(255) NULL,
  PRIMARY KEY (`id`, `membres_id`),
  INDEX `fk_telephones_membres1_idx` (`membres_id` ASC),
  CONSTRAINT `fk_telephones_membres1`
    FOREIGN KEY (`membres_id`)
    REFERENCES `projet_dev`.`membres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projet_dev`.`users_has_sandwiches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_dev`.`users_has_sandwiches` (
  `sandwiches_id` INT(10) UNSIGNED ZEROFILL NOT NULL,
  `membres_personne_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`sandwiches_id`, `membres_personne_id`),
  INDEX `fk_users_has_sandwiches_sandwiches1_idx` (`sandwiches_id` ASC),
  INDEX `fk_users_has_sandwiches_membres1_idx` (`membres_personne_id` ASC),
  CONSTRAINT `fk_users_has_sandwiches_sandwiches1`
    FOREIGN KEY (`sandwiches_id`)
    REFERENCES `projet_dev`.`sandwiches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_has_sandwiches_membres1`
    FOREIGN KEY (`membres_personne_id`)
    REFERENCES `projet_dev`.`membres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projet_dev`.`sandwiches_has_cartes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_dev`.`sandwiches_has_cartes` (
  `sandwiches_id` INT(10) UNSIGNED ZEROFILL NOT NULL,
  `cartes_id` INT NOT NULL,
  PRIMARY KEY (`sandwiches_id`, `cartes_id`),
  INDEX `fk_sandwiches_has_cartes_cartes1_idx` (`cartes_id` ASC),
  INDEX `fk_sandwiches_has_cartes_sandwiches1_idx` (`sandwiches_id` ASC),
  CONSTRAINT `fk_sandwiches_has_cartes_sandwiches1`
    FOREIGN KEY (`sandwiches_id`)
    REFERENCES `projet_dev`.`sandwiches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sandwiches_has_cartes_cartes1`
    FOREIGN KEY (`cartes_id`)
    REFERENCES `mydb`.`cartes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
